Repository SpiNNakerManchester/sPyNNaker8NewModelTemplate, pull requests merged in 2019-02, with the labels that each got.

#30 Enable testing with Python 3.7
  .travis.yml
Labels: BLOCKER!, bug

#25 Make import statements use PEP 328 better
  examples/my_example.py
  python_models8/__init__.py
  python_models8/connectors/my_connector.py
  python_models8/neuron/additional_inputs/my_additional_input.py
  python_models8/neuron/builds/my_model_curr_exp_my_additional_input.py
  python_models8/neuron/builds/my_model_curr_exp_my_threshold.py
  python_models8/neuron/builds/my_model_curr_my_synapse_type.py
  python_models8/neuron/neuron_models/my_neuron_model.py
  python_models8/neuron/plasticity/stdp/timing_dependence/my_timing_dependence.py
  python_models8/neuron/plasticity/stdp/weight_dependence/my_weight_dependence.py
  python_models8/neuron/synapse_types/my_synapse_type.py
Labels: enhancement, minor

#32 Update to use function argument rather than global define
  c_models/src/my_models/plasticity/stdp/weight_dependence/my_weight_impl.c
Labels: bug
