Repository SpiNNakerManchester/sPyNNaker8NewModelTemplate, pull requests merged in 2019-10, with the labels that each got.

#41 Test new models template
  examples/my_example.py
  nmt_integration_tests/__init__.py
  nmt_integration_tests/nwt_testbase.py
  nmt_integration_tests/test_my_full_neuron.py
  nmt_integration_tests/test_my_model_curr_exp.py
  nmt_integration_tests/test_my_model_curr_exp_my_input_type.py
  nmt_integration_tests/test_my_model_curr_exp_my_threshold.py
  nmt_integration_tests/test_my_model_curr_exp_stdp.py
  nmt_integration_tests/test_my_model_curr_my_additional_input.py
  nmt_integration_tests/test_my_model_curr_my_synapse_type.py
Labels: enhancement

#35 Fixes a bunch of small issues with the Python code
  _version.py
  python_models8/neuron/implementations/my_full_neuron_impl.py
  python_models8/neuron/neuron_models/my_neuron_model_incl_input_and_threshold.py
  python_models8/neuron/synapse_types/my_synapse_type.py
Labels: bug, minor

#34 Clean up the C code
  .gitignore
  c_models/.gitignore
  c_models/Debug/makefile
  c_models/src/my_models/additional_inputs/my_additional_input.h
  c_models/src/my_models/implementations/my_full_neuron_impl.h
  c_models/src/my_models/input_types/my_input_type.h
  c_models/src/my_models/models/my_neuron_model_impl.c
  c_models/src/my_models/plasticity/stdp/timing_dependence/my_timing_impl.c
  c_models/src/my_models/plasticity/stdp/timing_dependence/my_timing_impl.h
  c_models/src/my_models/plasticity/stdp/weight_dependence/my_weight_impl.c
  c_models/src/my_models/plasticity/stdp/weight_dependence/my_weight_impl.h
  c_models/src/my_models/synapse_types/synapse_types_my_impl.h
  c_models/src/my_models/threshold_types/my_threshold_type.h
Labels: enhancement, minor

#37 Constant
  python_models8/neuron/implementations/my_full_neuron_impl.py
  python_models8/neuron/plasticity/stdp/timing_dependence/my_timing_dependence.py
  python_models8/neuron/plasticity/stdp/weight_dependence/my_weight_dependence.py
Labels: enhancement, minor
