Repository SpiNNakerManchester/sPyNNaker8NewModelTemplate, pull requests merged in 2021-02, with the labels that each got.

#63 sPyNNaker8 no longer contributes code downstream
  .github/workflows/python_actions.yml
  README.md
  requirements.txt
  setup.py
Labels: enhancement

#65 moved neo_convertor
  nmt_integration_tests/nwt_testbase.py
Labels: enhancement

#66 End of Python 2.7 support
  python_models8/connectors/my_connector.py
  python_models8/neuron/additional_inputs/my_additional_input.py
  python_models8/neuron/builds/my_full_neuron.py
  python_models8/neuron/builds/my_if_curr_exp_sEMD.py
  python_models8/neuron/builds/my_model_curr_exp.py
  python_models8/neuron/builds/my_model_curr_exp_my_additional_input.py
  python_models8/neuron/builds/my_model_curr_exp_my_input_type.py
  python_models8/neuron/builds/my_model_curr_exp_my_threshold.py
  python_models8/neuron/builds/my_model_curr_my_synapse_type.py
  python_models8/neuron/implementations/my_full_neuron_impl.py
  python_models8/neuron/input_types/my_input_type.py
  python_models8/neuron/input_types/my_input_type_semd.py
  python_models8/neuron/neuron_models/my_neuron_model.py
  python_models8/neuron/plasticity/stdp/weight_dependence/my_weight_dependence.py
  python_models8/neuron/synapse_types/my_synapse_type.py
  python_models8/neuron/threshold_types/my_threshold_type.py
  requirements-test.txt
  setup.py
Labels: BLOCKER!, enhancement

#67 Test 3 9
  .github/workflows/c_actions.yml
  .github/workflows/python_actions.yml
  .ratexcludes
  CITATION.cff
  requirements-test.txt
  requirements.txt
  setup.py
Labels: enhancement, minor

#69 Update make references
  .github/workflows/python_actions.yml
  c_models/src/my_models/implementations/my_neuron_impl_semd.h
  c_models/src/my_models/synapse_types/synapse_types_my_impl.h
Labels: bug

#70 Test base2
  .github/workflows/python_actions.yml
  nmt_integration_tests/nwt_testbase.py
Labels: enhancement
